# Generated by Django 5.0.2 on 2026-06-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mês de Referência')),
                ('goal_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Meta Entradas')),
                ('goal_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Meta Saídas')),
                ('goal_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Meta Saldo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='financas.company')),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['-month'],
                'unique_together': {('company', 'month')},
            },
        ),
    ]
